spring.application.name=api
server.port=9001
#spring.datasource.url=jdbc:mysql://localhost:3306/stims?useSSL=false
#spring.datasource.username=root
#spring.datasource.password=00038150
#spring.jpa.hibernate.ddl-auto=update

#spring.application.name=api
#server.port=9002
spring.datasource.url=jdbc:mysql://MYSQL1003.site4now.net:3306/db_abd10f_stims?useSSL=false
spring.datasource.username=abd10f_stims
spring.datasource.password=00038150Mnce
spring.jpa.hibernate.ddl-auto=update

twilio.account.sid=SK5f0ab7d0ce694faade4a0f8051efcdd0
twilio.auth.token=5LREB9k0gl4RO10bymTPdYELojheFy8U
twilio.whatsapp.number=whatsapp:+14155238886

ikhokha.application.url=https://api.ikhokha.com/public-api/v1/api
ikhokha.application.id=IK8P0M7P9EUORGXVKFUFCXQXR066HLW1
ikhokha.application.key=3j25tifG7lKWNWaqQDF0cgOT2KCMsNo0